services:
  - type: web
    name: lets-play-backend
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn --worker-class eventlet -w 1 --bind 0.0.0.0:$PORT backend.main:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: DB_USER
        sync: false
      - key: DB_PASSWORD
        sync: false
      - key: DB_HOST
        sync: false
      - key: DB_NAME
        sync: false
      - key: DB_PORT
        value: 5432
      - key: DB_SSL
        value: "True"
      - key: SECRET_KEY
        generateValue: true
